services:
  db:
    image: postgres:16
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      TZ: America/Los_Angeles
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    image: node:20-alpine
    working_dir: /usr/src/app
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./api/.env.docker
    ports: ["6060:6060"]
    command: sh -c "npm run dev"
    volumes:
      - ./api:/usr/src/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports: ["4040:4040"]
    environment:
      VITE_API_BASE_URL: http://localhost:3000
    volumes:
      - ./client:/usr/src/app
      - client_node_modules:/usr/src/app/node_modules
    depends_on:
      - api

volumes:
  pgdata:
  client_node_modules:
